name: Django CI

on: [pull_request, push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Go to the backend directory and setup docker
      run: |
        cd backend
        docker compose up -d --build
    - name: Run Tests
      run: |
        docker compose run --rm django coverage run manage.py test
